### ISSUE TITLE
T15 Registering: bad DoB

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#19]
> Incorrect format of DOB entered

Result: Registers and directs to signin.php

should not register, but ask for user to fix dob (or should we try parsing it?)

**Comment by linnenbj** [comment]
It looks like it is difficult to enter a wrong dob.  As you are entering the information into the field, it will not let you enter a month > 12 or a day > 31.  The only thing that could possibly have bad input is the year field.

-My vote is to leave it as is.

**Comment by TheVulch** [comment]
Agreed - closingt this.

**Comment by cherun** [comment]
There might be a fix for this: https://stackoverflow.com/questions/17292087/limiting-date-range-in-html-5.
