### ISSUE TITLE
P1 Basic Website Functionality

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#2]
The "introduction screen" story, which seems to include deciding on the structure, tech, and theme of the website's front-end:

- [x] Create an intro page that contains an introduction / purpose
- [x] Create a button for the user to either enter login info or register

**Comment by TheVulch** [comment]
@mosspilot @Nejij I think you guys are doing this, right?

**Comment by mosspilot** [comment]
We completed this but found a bug
