### ISSUE TITLE
T19 Permissions page back/forward navigation messing things up

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#20]
> User hits back button, then forward button

Result: User is directed to permissions.php with a blank name field.  Not able to add or perform any actions, but able to navigate some of site and many errors pop up.

should work the same before/after navigating around the browser's history.

**Comment by linnenbj** [comment]
Fixed by testing permissions.php for a user session variable.  If one is not present, it just redirects back to the signin page.
