### ISSUE TITLE
T48 Not selecting any permissions for new app

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#26]
> No permissions checked off <in add_permissions.php>

Result: Directs to submit_permissions.php with error messages.  Still adds app to the database.

Should either...
- not throw any error messages, if an app with no permissions is fine, or...
- not allow the user to submit until at least 1(?) permission has been selected

**Comment by linnenbj** [comment]
Fixed.  Allowing a no permissions app to be created.
