### ISSUE TITLE
T51 Submit permissions page & browser navigation

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#27]
> Back, then forward <in submit_permissions.php>

Result: <Error...sometime during the test:> Execute failed: (1062) Duplicate entry '39-15' for key 'PRIMARY' 

We should be handling accidental db issues/browser history.

**Comment by mosspilot** [comment]
Plain english error checking is not implemented in this project as of yet. This is a valid response when a form is submitted twice and the database will not add another user account with the same unique key.

**Comment by linnenbj** [comment]
changed the sql statement to be INSERT IGNORE.  This fixed this error.
