### ISSUE TITLE
T58 Removing apps without an app chosen

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#28]
> Click “Remove Selected Apps…” without checking an app to be removed

Result: 
```
Notice: Undefined index: apps in /nfs/stak/students/l/linnenbj/public_html/se1/cs361projectb/test/submit_installed_remove.php on line 11

Warning: Cannot modify header information - headers already sent by (output started at /nfs/stak/students/l/linnenbj/public_html/se1/cs361projectb/test/submit_installed_remove.php:11) in /nfs/stak/students/l/linnenbj/public_html/se1/cs361projectb/test/submit_installed_remove.php on line 27
```

Obviously, this needs fixing. Just a simple patch making sure we actually have an app to remove would be good.

**Comment by mosspilot** [comment]
It doesn't appear that an implementation is complete for the removal of apps. More of an enhancement than bug

**Comment by linnenbj** [comment]
Fixed: redirects back to installed app list and gives a message saying you must select at least 1 app to remove.
