### ISSUE TITLE
T59 Viewing app permissions summaries not implemented

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#29]
> Click “View App Perm Summ” <in user_apps.php>

@sharkazm said:
> Not implemented yet, but I don’t think we need to do this given the list of installed apps that is already presented on this page.

Anyone have an opinion? I'm adding this as a bug, but someone can change it if they think it's not.

**Comment by TheVulch** [comment]
this is basically what's holding up #8 and #5 as well

**Comment by linnenbj** [comment]
a basic form of this has been implemented with appdetails.php now.  It fits in with our styling now as well.
