### ISSUE TITLE
P2 Collect Info

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#3]
The info-collecting story, where we are supposed to mine the web for info on our users. The original feature request were as follows:
- [ ] create data mining routine to find information about the user
- [ ] pull information using Facebook API
- [ ] interpret web history and installed apps to find public information

**Comment by TheVulch** [comment]
@sharkazm I think us two are on this one. As everyone discussed, it's not feasible to do most of it, though. Could you edit the issue to only have tasks that we are actually doing? I'm a bit fuzzy on what we decided on implementing for this story.

**Comment by sharkazm** [comment]
We are not actually mining the data.  I think what we figured last night is
we would just produce a table of booleans that show whether or not the app
requests permission to a specific data type.  This information would be
open source and entered by the users.

**Comment by TheVulch** [comment]
Wait a sec... basically just #5 ?

**Comment by sharkazm** [comment]
Yeah, thats my understanding.

**Comment by TheVulch** [comment]
So... we're conflating the two stories, then? Or are we just dropping this one?

**Comment by TheVulch** [comment]
I'll close this for now since we aren't doing anything here.
