### ISSUE TITLE
Adding no permissions to an app should not redirect to blank page

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#35]
Repro:

1. Start adding an app to the database like normal.
2. When you get to the add permissions section, don't select any, and submit.
3. You're shown a blank page on `submit_permissions.php` with an error.

We shouldn't let a user add an app without at least one initial permission. Or, we allow it, and it shouldn't be an error.

**Comment by linnenbj** [comment]
Fixed.  A bit of a hack fix in that I had to bypass the handle_request for permissions.  It seems like if permissions was empty, handle_request sends a die.  Functionality allows users to enter an app with no permissions.  A different notice is displayed for apps created with permissions and apps without.
