### ISSUE TITLE
Redo Add App flow

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#37]
Right now, adding an app requires us first typing in a hypothetical name to verify that the name is not already being used by another app.  
However, the validation of uniqueness for a new app is now both the name and the platform - since, obviously, apps on different platforms could have different permissions.  
This has lead to an agreement that the flow should be changed, and that the first page validating the app name will be removed. Instead, the app name will be entered along with the rest on `newapp.php`, and when the user submits the form, we will validate it and alert the user if something is not valid.

**Comment by linnenbj** [comment]
I've done some work on this and committed some stuff to this branch.  I believe I have it working properly, but should probably be tested a bit more.
**NOTE: the apps table in the database has to change for this to work.  I've updated both the table creation and prepopulation sql files to reflect work with these changes.

Might be ready for close?  Would just like a double check.

**Comment by linnenbj** [comment]
merged and working.
