### ISSUE TITLE
P3 User App Management

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#4]
Concerning the story where users can add & remove references to mobile apps on their account.
- [x] create a database to store app information
- [x] create a database to store user’s installed apps
- [x] be able to add / remove entries from user’s account
- [x] Show user if the app they are entering is already in database or not
- [ ] Integrate pages with current Bootstrap/PHP scheme

**Comment by TheVulch** [comment]
@cherun I guess this is your and your programming partner's part for this week (when he's added to repo members, could someone reference him on this issue so he gets updates?). Not sure which tasks you guys decided to do, so I just copied what I got from the email to our customer about prioritizing stories.

**Comment by cherun** [comment]
We created a database for the 1st bullet on Wednesday and shared the .sql files and ER diagram with everyone then. I shared those with @sharkazm for P2, so we'll see what changes will be made to the database design and edit our front-end from there. We're working on the 4th bullet right now.
I just pushed the relevant files to a new branch in the repository (called p3).

**Comment by cherun** [comment]
As for the 2nd bullet, we did design for it in the database, as a third table between users and apps. Don't know if it should be a separate database or in the same one.

**Comment by TheVulch** [comment]
Hey @cherun can I take this over and integrate your code with the stuff from #7 ? Or do you guys need to do more work?

**Comment by cherun** [comment]
This should be good to go. I've merged the .sql files in the p3 branch into the master branch.

**Comment by TheVulch** [comment]
Okay great. Is the schema updated from last Saturday's meeting? We discussed the email being the user's username, but I dont see that in #11

**Comment by TheVulch** [comment]
@linnenbj finished this up on the add-app-jim branch already in a0f561aa31f9e5b7ade97844ddc43ff877686b0d .
