### ISSUE TITLE
P6 Login Functionality

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#7]
We need some basic authorization/authentication in our website. As with P5, surprised it wasn't more important to the customer. Oh well.
- [x] create a screen for user to enter login information
- [x] check entered credentials against database
- [x] provide feedback (login success / fail)
- [x] start a session and move user to the user’s main app page

**Comment by TheVulch** [comment]
@mosspilot @sharkazm As in #6 , I think you guys need to figure out who's doing what.

**Comment by sharkazm** [comment]
I don't care which one we use, as long as it works.  I know that one of
them has been working since Monday.

**Comment by TheVulch** [comment]
I'll be working on this one right now, trying to integrate @sharkazm 's material with @mosspilot 's stuff.

**Comment by TheVulch** [comment]
As of [now](https://github.com/mosspilot/cs361projectb/tree/95bb2a16aaad35636676c8631746d82d9a4dde80), we have a basic implementation of all of these items, so I'll consider this closed.
