### ISSUE TITLE
Bootstrap issues on desktop

### ISSUE THREAD

**Issue by TheVulch** [mosspilot/cs361projectb#9]
Seems bootstrap's CSS isn't perfect. The login form is off:
![screenshot 4](https://cloud.githubusercontent.com/assets/5877394/8989487/6cb83ab4-36a1-11e5-9128-baf9ee152a70.png)

Still functional, though. Same thing with the register form:
![screenshot 5](https://cloud.githubusercontent.com/assets/5877394/8989523/8f1a3986-36a1-11e5-9c86-cc9c2799ad22.png)

I'm testing on Win 8.1 Chrome 44 . I'll check out later if Arch (Linux) is acting up too.  
I think @mosspilot you were the Bootstrap guy? Anyways, I guess it's whoever's working on #2 .

**Comment by mosspilot** [comment]
Jesse and I were working with it and yes it has been a struggle
